#!/home/zhengjh/miniconda3/envs/r403/bin/Rscript
# parameter

library(optparse)
library(getopt)

option_list <- list(
  make_option(c("-o", "--output"), type = "character", default = FALSE,
              action = "store", help = "This is the output directory."
  ),
  make_option(c("-t", "--Type"), type = "character", default = "10X",
              action = "store", help = "This is type of exp matrix, default is 10X, the other is .csv which row is gene, column is cell."
  ),
  make_option(c("--datapath"), type = "character", default = FALSE,
              action = "store", help = "This is the path of exp matrix."
  ),
  
  make_option(c("--project_name"), type = "character", default = FALSE,
              action = "store", help = "This is project name built in seurat object and the pre_fix of files generated by this function."
  ),
  make_option(c("--mt_pattern"), type = "character", default = "^mt-",
              action = "store", help = "This is mitochondria pattern used to calculate its percentage, default is the ^mt-."
  ),
  make_option(c("--rb_pattern"), type = "character", default = "^Rpl|^Rps",
              action = "store", help = "This is ribosome pattern used to calculate its percentage, default is ^Rpl|^Rps"
  ),
  
  make_option(c("--min_cell"), type = "integer", default = 3,
              action = "store", help = "This is min cells number to filter, default is 3."
  ),
  make_option(c("--min_gene"), type = "integer", default = 0,
              action = "store", help = "This is min gene number to filter, default is 0."
  )
  )

# -help 
opt = parse_args(OptionParser(option_list = option_list, 
                              usage = "This Script is general overview data quality of single cell exp matrix!"))
print(opt)

#### step0.load data ####

source("/home/zhengjh/scripts/seurat/function/SeuratWrapperFunction.R")

print("Step0: Load Data")
##### step00. load functions ####
# read in the functions
timestart<-Sys.time() 
# set the output path
cat("Current working dir: ", opt$output)
cat("\n")
setwd(opt$output)
# load ref object

#### step01. load exp matrix ####

print("Step0: Load exp matrix data")
if(opt$Type=="10X"){
  print("Read exp matrix from 10X cellranger output")
  exp_count <- Read10X(data.dir = opt$datapath)
  print("The rownum and colnum of  exp_count is ")
  print(dim(exp_count))
}else{
  print("Read exp matrix from csv file")
  exp_count <- read.csv(opt$datapath, header = T, row.names = 1) 
  print("The rownum and colnum of normal exp is ")
  print(dim(exp_count))
}


#### step1: Create_seurat_filter_cell ######
print("Step1: Creat Seuart Object with filtering lower genes and lower cells")
Or_ident <- rep(opt$project_name, ncol(exp_count))
exp_count.seurat <- CreateFirstFilterSeuratObject(exp_count, opt$project_name, opt$min_cell, opt$min_gene,
                                                   opt$mt_pattern, opt$rb_pattern)

print("The row_num and col_num of the first filtered matrix:")
print(dim(exp_count.seurat))
print("The cellnumber of samples:")
print(table(exp_count.seurat$orig.ident))

#### step2: Overview of the data quality ######
print("Step2: Overview of the data quality")
name_pre <- paste0(opt$project_name,"filter_gene_expressed", opt$min_cell, "cells", opt$min_gene, "genes", sep = "_") 
exp_count.seurat <- SeuratQC(exp_count.seurat, name_pre)
rds_name <- paste0(opt$project_name, "_dataquality_overview_seurat.rds")
saveRDS(exp_count.seurat, file = rds_name)

print("Happy~Finished!!!")
timeend<-Sys.time()
runningtime<-timeend-timestart
print(runningtime)





